-- CreateTable
CREATE TABLE "Candidate" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "cellPhone" TEXT,
    "nationality" TEXT NOT NULL,
    "currentLocation" TEXT NOT NULL,
    "dateOfBirth" DATETIME,
    "gender" TEXT,
    "maritalStatus" TEXT,
    "currentPosition" TEXT,
    "experience" INTEGER,
    "education" TEXT,
    "technicalSkills" TEXT,
    "languageProficiency" TEXT,
    "certifications" TEXT,
    "culturalBackground" TEXT,
    "workStylePreference" TEXT,
    "communicationStyle" TEXT,
    "adaptabilityScore" REAL,
    "teamworkOrientation" TEXT,
    "leadershipStyle" TEXT,
    "conflictResolution" TEXT,
    "timeManagement" TEXT,
    "waHarmonyAlignment" REAL DEFAULT 0,
    "kaizenMindset" REAL DEFAULT 0,
    "omotenashiService" REAL DEFAULT 0,
    "bushidoDedication" REAL DEFAULT 0,
    "nemawashiConsensus" REAL DEFAULT 0,
    "candidateStatus" TEXT NOT NULL DEFAULT 'REGISTERED',
    "availabilityDate" DATETIME,
    "salaryExpectation" INTEGER,
    "preferredLocation" TEXT,
    "visaStatus" TEXT
);

-- CreateTable
CREATE TABLE "Company" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "companyName" TEXT NOT NULL,
    "industry" TEXT NOT NULL,
    "companySize" TEXT NOT NULL,
    "headquarters" TEXT NOT NULL,
    "website" TEXT,
    "description" TEXT,
    "corporateCulture" TEXT,
    "workEnvironment" TEXT,
    "managementStyle" TEXT,
    "communicationStyle" TEXT,
    "diversityPolicy" TEXT,
    "waHarmonyImportance" REAL DEFAULT 0,
    "kaizenImplementation" REAL DEFAULT 0,
    "omotenashiStandards" REAL DEFAULT 0,
    "hierarchyStructure" TEXT,
    "consensusDecisionMaking" REAL DEFAULT 0,
    "revenue" BIGINT,
    "foundedYear" INTEGER,
    "employeeCount" INTEGER,
    "businessModel" TEXT,
    "competitiveAdvantage" TEXT,
    "preferredCandidateProfile" TEXT,
    "culturalRequirements" TEXT,
    "languageRequirements" TEXT
);

-- CreateTable
CREATE TABLE "JobPosting" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "jobTitle" TEXT NOT NULL,
    "department" TEXT,
    "location" TEXT NOT NULL,
    "employmentType" TEXT NOT NULL,
    "experienceLevel" TEXT NOT NULL,
    "jobDescription" TEXT NOT NULL,
    "responsibilities" TEXT,
    "requirements" TEXT,
    "qualifications" TEXT,
    "technicalSkills" TEXT,
    "salaryRangeMinimum" INTEGER,
    "salaryRangeMaximum" INTEGER,
    "benefits" TEXT,
    "bonusStructure" TEXT,
    "culturalFitRequirements" TEXT,
    "languageRequirements" TEXT,
    "communicationStyle" TEXT,
    "teamworkExpectation" TEXT,
    "leadershipExpectation" TEXT,
    "waHarmonyRequired" REAL DEFAULT 0,
    "kaizenParticipation" REAL DEFAULT 0,
    "omotenashiExpectation" REAL DEFAULT 0,
    "hierarchyRespect" REAL DEFAULT 0,
    "consensusBuilding" REAL DEFAULT 0,
    "postingStatus" TEXT NOT NULL DEFAULT 'active',
    "applicationDeadline" DATETIME,
    "startDate" DATETIME,
    "urgencyLevel" TEXT,
    "companyId" TEXT NOT NULL,
    CONSTRAINT "JobPosting_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CulturalAssessment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "candidateId" TEXT NOT NULL,
    "assessmentType" TEXT NOT NULL,
    "assessmentDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "overallScore" REAL NOT NULL,
    "culturalFitPrediction" REAL NOT NULL,
    "integrationTimelineDays" INTEGER NOT NULL,
    "waHarmonyScore" REAL NOT NULL DEFAULT 0,
    "kaizenImprovementScore" REAL NOT NULL DEFAULT 0,
    "omotenashiServiceScore" REAL NOT NULL DEFAULT 0,
    "bushidoDedicationScore" REAL NOT NULL DEFAULT 0,
    "nemawashiConsensusScore" REAL NOT NULL DEFAULT 0,
    "honneTatemaeBalance" REAL NOT NULL DEFAULT 0,
    "indirectCommunication" REAL NOT NULL DEFAULT 0,
    "nonverbalAwareness" REAL NOT NULL DEFAULT 0,
    "silenceComfort" REAL NOT NULL DEFAULT 0,
    "contextualUnderstanding" REAL NOT NULL DEFAULT 0,
    "senpaiKohaiRespect" REAL NOT NULL DEFAULT 0,
    "authorityRecognition" REAL NOT NULL DEFAULT 0,
    "formalityAdherence" REAL NOT NULL DEFAULT 0,
    "statusAwareness" REAL NOT NULL DEFAULT 0,
    "hierarchyNavigation" REAL NOT NULL DEFAULT 0,
    "groupHarmonyPriority" REAL NOT NULL DEFAULT 0,
    "collectiveDecisionMaking" REAL NOT NULL DEFAULT 0,
    "consensusBuilding" REAL NOT NULL DEFAULT 0,
    "teamLoyalty" REAL NOT NULL DEFAULT 0,
    "groupAccountability" REAL NOT NULL DEFAULT 0,
    "dedicationToWork" REAL NOT NULL DEFAULT 0,
    "qualityFocus" REAL NOT NULL DEFAULT 0,
    "continuousImprovement" REAL NOT NULL DEFAULT 0,
    "attentionToDetail" REAL NOT NULL DEFAULT 0,
    "processAdherence" REAL NOT NULL DEFAULT 0,
    "punctualityImportance" REAL NOT NULL DEFAULT 0,
    "timeRespect" REAL NOT NULL DEFAULT 0,
    "scheduleAdherence" REAL NOT NULL DEFAULT 0,
    "planningOrientation" REAL NOT NULL DEFAULT 0,
    "deadlineCommitment" REAL NOT NULL DEFAULT 0,
    "relationshipInvestment" REAL NOT NULL DEFAULT 0,
    "trustBuilding" REAL NOT NULL DEFAULT 0,
    "longTermOrientation" REAL NOT NULL DEFAULT 0,
    "loyaltyDemonstration" REAL NOT NULL DEFAULT 0,
    "networkMaintenance" REAL NOT NULL DEFAULT 0,
    "changeAcceptance" REAL NOT NULL DEFAULT 0,
    "flexibilityInApproach" REAL NOT NULL DEFAULT 0,
    "learningOrientation" REAL NOT NULL DEFAULT 0,
    "culturalAdaptability" REAL NOT NULL DEFAULT 0,
    "resilienceInChallenges" REAL NOT NULL DEFAULT 0,
    "professionalEtiquette" REAL NOT NULL DEFAULT 0,
    "businessCardProtocol" REAL NOT NULL DEFAULT 0,
    "meetingParticipation" REAL NOT NULL DEFAULT 0,
    "presentationSkills" REAL NOT NULL DEFAULT 0,
    "clientServiceOrientation" REAL NOT NULL DEFAULT 0,
    "creativeThinking" REAL NOT NULL DEFAULT 0,
    "innovationBalance" REAL NOT NULL DEFAULT 0,
    "riskAssessment" REAL NOT NULL DEFAULT 0,
    "dimensionScores" TEXT,
    "culturalTrainingNeeded" TEXT,
    "assessmentNotes" TEXT,
    CONSTRAINT "CulturalAssessment_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PsychologicalAssessment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "candidateId" TEXT NOT NULL,
    "assessmentType" TEXT NOT NULL,
    "assessmentDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "openness" REAL,
    "conscientiousness" REAL,
    "extraversion" REAL,
    "agreeableness" REAL,
    "neuroticism" REAL,
    "logicalReasoning" REAL,
    "numericalAbility" REAL,
    "verbalAbility" REAL,
    "spatialAbility" REAL,
    "memoryCapacity" REAL,
    "selfAwareness" REAL,
    "selfRegulation" REAL,
    "motivation" REAL,
    "empathy" REAL,
    "socialSkills" REAL,
    "stressResilience" REAL,
    "teamworkAbility" REAL,
    "leadershipPotential" REAL,
    "adaptability" REAL,
    "problemSolving" REAL,
    "overallScore" REAL NOT NULL,
    "recommendations" TEXT,
    "assessmentNotes" TEXT,
    CONSTRAINT "PsychologicalAssessment_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "LanguageAssessment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "candidateId" TEXT NOT NULL,
    "language" TEXT NOT NULL,
    "assessmentDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assessmentType" TEXT NOT NULL,
    "speakingLevel" TEXT NOT NULL,
    "listeningLevel" TEXT NOT NULL,
    "readingLevel" TEXT NOT NULL,
    "writingLevel" TEXT NOT NULL,
    "overallScore" REAL NOT NULL,
    "speakingScore" REAL,
    "listeningScore" REAL,
    "readingScore" REAL,
    "writingScore" REAL,
    "businessCommunication" REAL,
    "technicalVocabulary" REAL,
    "presentationSkills" REAL,
    "negotiationSkills" REAL,
    "certificationLevel" TEXT,
    "certificationDate" DATETIME,
    "assessmentNotes" TEXT,
    CONSTRAINT "LanguageAssessment_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ProfessionalAssessment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "candidateId" TEXT NOT NULL,
    "assessmentType" TEXT NOT NULL,
    "assessmentDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "technicalProficiency" REAL,
    "toolsAndTechnologies" TEXT,
    "industryKnowledge" REAL,
    "problemSolvingAbility" REAL,
    "innovationCapability" REAL,
    "projectManagement" REAL,
    "teamLeadership" REAL,
    "clientManagement" REAL,
    "strategicThinking" REAL,
    "analyticalSkills" REAL,
    "domainExpertise" REAL,
    "regulatoryKnowledge" REAL,
    "marketUnderstanding" REAL,
    "competitorAwareness" REAL,
    "overallScore" REAL NOT NULL,
    "skillGaps" TEXT,
    "developmentPlan" TEXT,
    "assessmentNotes" TEXT,
    CONSTRAINT "ProfessionalAssessment_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "InterviewSession" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "candidateId" TEXT NOT NULL,
    "applicationId" TEXT,
    "interviewType" TEXT NOT NULL,
    "interviewRound" INTEGER NOT NULL,
    "interviewDate" DATETIME NOT NULL,
    "duration" INTEGER,
    "technicalScore" REAL,
    "culturalFitScore" REAL,
    "communicationScore" REAL,
    "motivationScore" REAL,
    "overallScore" REAL NOT NULL,
    "strengths" TEXT,
    "weaknesses" TEXT,
    "recommendations" TEXT,
    "interviewNotes" TEXT,
    "recommendation" TEXT NOT NULL,
    "interviewerName" TEXT,
    "interviewerRole" TEXT,
    CONSTRAINT "InterviewSession_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "InterviewSession_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "OnboardingRecord" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "candidateId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "startDate" DATETIME NOT NULL,
    "onboardingStatus" TEXT NOT NULL,
    "documentationComplete" BOOLEAN NOT NULL DEFAULT false,
    "systemAccessGranted" BOOLEAN NOT NULL DEFAULT false,
    "trainingCompleted" BOOLEAN NOT NULL DEFAULT false,
    "culturalOrientationDone" BOOLEAN NOT NULL DEFAULT false,
    "mentorAssigned" BOOLEAN NOT NULL DEFAULT false,
    "culturalAdaptationScore" REAL,
    "integrationChallenges" TEXT,
    "supportProvided" TEXT,
    "expectedCompletionDate" DATETIME,
    "actualCompletionDate" DATETIME,
    "onboardingNotes" TEXT,
    CONSTRAINT "OnboardingRecord_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "OnboardingRecord_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PerformanceReview" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "candidateId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "reviewPeriod" TEXT NOT NULL,
    "reviewDate" DATETIME NOT NULL,
    "reviewType" TEXT NOT NULL,
    "technicalPerformance" REAL,
    "culturalIntegration" REAL,
    "teamCollaboration" REAL,
    "communicationSkills" REAL,
    "goalAchievement" REAL,
    "overallPerformance" REAL NOT NULL,
    "culturalFitImprovement" REAL,
    "japaneseBusinessEtiquette" REAL,
    "teamHarmonyContribution" REAL,
    "achievements" TEXT,
    "areasForImprovement" TEXT,
    "developmentGoals" TEXT,
    "reviewerName" TEXT,
    "reviewerRole" TEXT,
    "reviewNotes" TEXT,
    CONSTRAINT "PerformanceReview_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PerformanceReview_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CandidateStatusHistory" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "candidateId" TEXT NOT NULL,
    "previousStatus" TEXT NOT NULL,
    "newStatus" TEXT NOT NULL,
    "changeReason" TEXT,
    "changedBy" TEXT,
    "notes" TEXT,
    CONSTRAINT "CandidateStatusHistory_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Application" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "candidateId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "jobPostingId" TEXT NOT NULL,
    "applicationStatus" TEXT NOT NULL DEFAULT 'pending',
    "applicationDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "overallMatchScore" REAL,
    "technicalMatchScore" REAL,
    "culturalFitScore" REAL,
    "languageMatchScore" REAL,
    "experienceMatchScore" REAL,
    "resumeUrl" TEXT,
    "coverLetterUrl" TEXT,
    "portfolioUrl" TEXT,
    "finalDecision" TEXT,
    "decisionDate" DATETIME,
    "decisionReason" TEXT,
    "applicationNotes" TEXT,
    CONSTRAINT "Application_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Application_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Application_jobPostingId_fkey" FOREIGN KEY ("jobPostingId") REFERENCES "JobPosting" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "MarketIntelligence" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "dataType" TEXT NOT NULL,
    "industry" TEXT NOT NULL,
    "location" TEXT NOT NULL,
    "timeframe" TEXT NOT NULL,
    "averageSalary" REAL,
    "salaryRange" TEXT,
    "demandLevel" TEXT NOT NULL,
    "supplyLevel" TEXT NOT NULL,
    "inDemandSkills" TEXT,
    "emergingSkills" TEXT,
    "decliningSkills" TEXT,
    "culturalTrends" TEXT,
    "adaptationChallenges" TEXT,
    "successFactors" TEXT,
    "dataSource" TEXT,
    "reliability" REAL,
    "marketNotes" TEXT
);

-- CreateTable
CREATE TABLE "SystemMetrics" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metricType" TEXT NOT NULL,
    "metricName" TEXT NOT NULL,
    "metricValue" REAL NOT NULL,
    "metricUnit" TEXT,
    "timeframe" TEXT,
    "category" TEXT,
    "subcategory" TEXT,
    "calculationMethod" TEXT,
    "dataPoints" INTEGER,
    "confidence" REAL,
    "metricNotes" TEXT
);

-- CreateTable
CREATE TABLE "ReportGeneration" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "reportType" TEXT NOT NULL,
    "reportTitle" TEXT NOT NULL,
    "reportFormat" TEXT NOT NULL,
    "candidateId" TEXT,
    "companyId" TEXT,
    "dateRange" TEXT,
    "filters" TEXT,
    "generationStatus" TEXT NOT NULL,
    "generatedAt" DATETIME,
    "reportUrl" TEXT,
    "reportSize" INTEGER,
    "keyFindings" TEXT,
    "recommendations" TEXT,
    "dataPoints" INTEGER,
    "requestedBy" TEXT,
    "reportNotes" TEXT
);

-- CreateIndex
CREATE UNIQUE INDEX "Candidate_email_key" ON "Candidate"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Company_companyName_key" ON "Company"("companyName");
